AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bigmouth
  
  Sample SAM Template for bigmouth

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  GetIndexPageFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
      # BuildMethod: go1.x
        
    Properties:
      CodeUri: ./
      Handler: bootstrap
      # Handler: get-index-page
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:        
        GetIndexPageApi:
          Type: Api
          Properties:
            Path: /
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BigMouthAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/FUNCTION_PATH"
  # HelloWorldFunction:
  #   Description: "First Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
